# Generated by Django 6.0.6 on 2026-07-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_type',
            field=models.CharField(blank=True, help_text='Example: Web Application, E-commerce, API', max_length=100),
        ),
    ]
